project:
  type: website

website:
  google-analytics: "G-JRHMPYF406"
  favicon: images/logo.png
  title: "Homes by Quintana"   # keep this one for browser tab title
  description: "Helping buyers and sellers ..."
  sidebar:
    logo: images/logo.png
    pinned: false
    style: floating
    search: false
    contents:
      - text: Home
        href: index.qmd
      - text: Marketing Insights
        href: marketing-insights.qmd
      - text: Market Report
        href: market-report.qmd
      - text: Price Your Home
        href: https://slyfoxx84.shinyapps.io/house-prices-advanced-regression-techniques/
      - text: Buyer & Seller Insights
        href: buyer-seller-insights.qmd
      - text: Templates
        href: templates.qmd
      - text: About Me
        href: about.qmd
      - text: Contact
        href: contact.qmd
